### ISSUE TITLE
TODO - "Quest-Mission-Event-Task"

### ISSUE THREAD

**Issue by mattyx14** [mattyx14/dkkserv#1]
### TODO LIST

**QUEST**
- [x] Golden Key #3135 -- Fynn Quest
- [x] Golden Key #3136 -- Misidia Quest
- [x] Basic Knight Equip -- "No Drop" - Sohan Quest 
- [x] Basic Pally Equip -- "No Drop" - Fynn Quest 
- [x] Basic Mage Equip -- "No Drop" - Mer Jungle Quest 
- [x] Blue Quest-- "No Drop" -- Fynn & Anshara Quest
- [x] Magma Set -- "No Drop" -- Fynn Quest
- [x] Lightning Set -- "No Drop" -- Anshara Quest

**MOUNTS**
- [x] Panther -- "No Drop" -- Mer Jungle Mount
- [x] Donkey -- "No Drop" -- Fynn Mount
- [x] Undead Cavebear -- "No Drop" -- Anshara Mount

**MISSIONS**
- [x] Rose Colors Mission Misidia
- [x] Knight Axe -- First Sacrifice "No Drop" -- Fynn
- [x] Dragon Hammer -- First Sacrifice "No Drop" -- Jorvik
- [x] Wyvern Fang -- First Sacrifice "No Drop" -- Misidia
- [x] Fire Axe -- First Sacrifice "No Drop" -- Elfic
- [x] Skull Staff -- First Sacrifice "No Drop" -- Anshara
- [x] Bright Sword -- First Sacrifice "No Drop" -- Misidia
- [x] Black Knight Mission -- Team 5 -- Mer Jungle
- [x] Behemoth Quest -- "No Drop" -- Anshara
- [x] Demon Helmet -- Team 5 -- Fynn Quest
- [x] Djinn Lamps
> **Requeriment:** Sacrifice: Wyvern Fang, Knight Axe & Dragon Hammer Quest's
- [x] Dracula Mission
> **Requeriment 1:** Sacrifice: Bright Sword, Fire Axe & Skull Staff Quest's
- [x] Pirate Outfit Mission -- Fynn & Misidia
> **Requeriment:** Pirate Key #2088 & #2090
- [x] Conjurer Outfit -- Fynn & Misidia
> **Requeriment:** Magic Key #2585 to #2587 & Rose Colors Mission
- [x] Djinns -- Anshara
> **Requeriment 1:** Sacrifice ( Wyvern Fang, Knight Axe & Dragon Hammer )
> **Requeriment 2:** Complete Quest ( Reserved Anshara )
- [x] Arus Weapons (Justice Seeker & Blessed Sceptre & Royal Axe)
> **Requeriment:** Complete Sacrifice ( Bright Sword, Fire Axe & Skull Staff )
- [x] The Pits of Inferno
> **Requeriment:** Complete: Annihilator Mission

**EVENTS**
- [x] Rose Colors (Restard Server)
- [x] Annihilator (Restard Server)
> **Requeriment 1:** Complete the: Vampire's signet ring, Djinn Mission, Arus Weapons Missions, Pirate Outfit, Conjurer Outfit, Death Herald Outfit & Assassin Outfit
> **Requeriment 2:** Annihilator Key #2092 & Demon Helmet Quest
- [x] Item Rewards for level up
- [x] Item Rewards for kill bosses

**MONSTERS**
- [x] New formate loot to all monsters
- [x] New formate spells to all monsters
- [x] Try add all monsters from Tibia CipSoft (DarkKonia Style)
