### ISSUE TITLE
TODO - "Quest-Mission-Event-Task" - Second Mode

### ISSUE THREAD

**Issue by mattyx14** [mattyx14/dkkserv#3]
### TODO LIST

**QUEST**

**MOUNTS**

**MISSIONS**

**EVENTS**

**TASK**
- [ ] Addon Items

**ITEMS**

**MONSTERS**

**MAP**
- [ ] Gray Beach (DarkKonia Style)
- [ ] Roshamull (DarkKonia Style)
- [ ] Oramond (DarkKonia Style)
